OPTIONS http://localhost:4000/api/sensors HTTP/1.1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMyMSwiaWF0IjoxNTk3NjAwNzgwLCJleHAiOjE1OTgyMDU1ODB9.Z_E_o7SegTFgf5NE9uM1JNRDCrTUXOGGL7iMlLul560


{
  "data": [
    {
      "name": "Outside_Temperature",
      "value": "4.8",
      "place": "Outside",
      "thinggg": "qwepoi"
    },
    {
      "name": "inside_humidity",
      "value": "4,8",
      "place": "inside"
    },
    {
      "name": "inside_temperature",
      "value": "4,8",
      "place": "outside"
    }
  ]
}