GET http://localhost:4000/api/sensors HTTP/1.1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIxLCJvd25lciI6ImJvYnNvbiIsImlhdCI6MTU5ODc5NjIwOSwiZXhwIjoxNTk5NDAxMDA5fQ._KIr9E0E8kNWAaHSl0C-0l3osKJulgN1YcYqGw4VVfw


{
  "data": [
    {
      "name": "Outside_Temperature",
      "value": "4.8",
      "place": "Outside",
      "thinggg": "qwepoi"
    },
    {
      "name": "inside_humidity",
      "value": "4,8",
      "place": "inside"
    },
    {
      "name": "inside_temperature",
      "value": "4,8",
      "place": "outside"
    }
  ]
}